name: 2. Tests on Local vPOD

on:
  workflow_dispatch:
    inputs:
      test_env:
        type: choice
        description: "Testing environment"
        required: false
        default: 'Local'
        options:
        - Local
        - Paperspace
      docker_image:
        type: string
        description: "Docker image used in notebook testing"
        required: false
        default: "graphcore/pytorch-jupyter:3.2.0-ubuntu-20.04-20230314"
      notebooks:
        type: string
        description: "List of notebooks to test in JSON format"
        required: false
        default: '["Graphcore-HuggingFace-README_first"]'
  push:
  schedule:
    # run at 11:00 PM GMT every night
    - cron:  '0 23 * * *'


jobs:
  tests:
    uses: graphcore/paperspace-automation/.github/workflows/subwf-vpod-tests-for-nb-repo.yml@main
    with:
      docker_image: ${{ inputs.docker_image || 'graphcore/pytorch-jupyter:3.2.0-ubuntu-20.04-20230314' }}
      notebooks: ${{ inputs.notebooks }}
      machine_types: '["IPU-POD4"]'
      test_env: ${{ inputs.test_env || 'Local' }}
    secrets:
      gh_token:  ${{ secrets.GH_TOKEN_SYNC_REPOS }}
#      paperspace_api_key: ${{ secrets.paperspace_api_key }}
#      hugging_face_hub_token: ${{ secrets.hugging_face_hub_token }}
      slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
      ci_slack_channel_id: ${{ secrets.CI_SLACK_CHANNEL_ID }}
